services:
  - type: web
    name: healthtimeout-posture-api
    env: python
    plan: free
    runtime: python-3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
